"""Render visual-regression views of the saved v001 door test model."""

from __future__ import annotations

import os

import FreeCAD as App
import FreeCADGui as Gui
import ArchWindow
from PySide import QtCore, QtWidgets


HERE = os.path.dirname(os.path.abspath(__file__))
PURISCAL_DIR = os.path.dirname(HERE)
MACROS_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(PURISCAL_DIR)))
MODEL_PATH = os.path.join(MACROS_ROOT, ".codex_tmp", "ElectricCR_PuertaDobleBIM_Puriscal_v001.FCStd")
CAPTURE_DIR = os.path.join(PURISCAL_DIR, "capturas")


def save_view(view, orientation, filename):
    getattr(view, orientation)()
    # Standard-view changes are animated in this FreeCAD profile. Let that
    # transition finish before fitting, otherwise the capture records a
    # half-rotated camera and an incorrect bounding box.
    for _ in range(50):
        Gui.updateGui()
        QtWidgets.QApplication.processEvents()
        QtCore.QThread.msleep(20)
    view.fitAll()
    view.redraw()
    for _ in range(10):
        Gui.updateGui()
        QtWidgets.QApplication.processEvents()
        QtCore.QThread.msleep(20)
    try:
        view.getCameraNode().scaleHeight(1.15)
    except Exception:
        pass
    Gui.updateGui()
    path = os.path.join(CAPTURE_DIR, filename)
    view.saveImage(path, 1600, 1000, "White")
    if not os.path.exists(path) or os.path.getsize(path) == 0:
        raise RuntimeError("No se pudo guardar la captura: " + path)
    print("CAPTURE_OK", path)


os.makedirs(CAPTURE_DIR, exist_ok=True)
doc = App.openDocument(MODEL_PATH)
doc.recompute()
door = doc.getObject("Window")
if door is None:
    raise RuntimeError("No se encontro la puerta BIM en el archivo de prueba.")

# The smoke model is intentionally generated by FreeCADCmd. Arch objects made
# there have no GUI view-provider until a GUI process explicitly installs it.
if not getattr(door.ViewObject, "Proxy", None) or not hasattr(
    door.ViewObject.Proxy, "colorize"
):
    ArchWindow._ViewProviderWindow(door.ViewObject)

door.SymbolPlan = False
door.SymbolElevation = False
door.Opening = 0
doc.recompute()
ArchWindow.recolorize(door)
App.Console.PrintMessage("MATERIAL_NAMES " + repr(list(door.Material.Names)) + "\n")
for mat in door.Material.Materials:
    App.Console.PrintMessage("MATERIAL_DATA " + mat.Label + " " + repr(mat.Material) + "\n")
appearance = door.ViewObject.ShapeAppearance
unique_appearance = sorted(
    {
        (
            tuple(round(channel, 3) for channel in item.DiffuseColor),
            round(float(item.Transparency), 3),
        )
        for item in appearance
    }
)
App.Console.PrintMessage(
    "SHAPE_APPEARANCE " + str(len(appearance)) + " " + repr(unique_appearance) + "\n"
)
if len(unique_appearance) < 3:
    raise RuntimeError(
        "La apariencia no distingue marco, panel inferior y vidrio: "
        + repr(unique_appearance)
    )
view = Gui.activeDocument().activeView()
save_view(view, "viewFront", "PuertaDobleBIM_v001_frontal_cerrada.png")

door.Opening = 25
doc.recompute()
ArchWindow.recolorize(door)
save_view(view, "viewAxonometric", "PuertaDobleBIM_v001_axonometrica_apertura25.png")

door.SymbolPlan = True
doc.recompute()
ArchWindow.recolorize(door)
save_view(view, "viewTop", "PuertaDobleBIM_v001_planta_apertura25.png")

App.closeDocument(doc.Name)
QtCore.QTimer.singleShot(250, QtWidgets.QApplication.instance().quit)
